[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.14",
    "logging>=0.4.9.6",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]
